### ISSUE TITLE
pkexec doesn't follow user's interface theme

### ISSUE THREAD

**Issue by shvchk** [marciosouza20/zulucrypt#1]
`zuluCrypt-gui-pkexec` doesn't use my interface theme, so it looks like this:
![screenshot_20161206_203256](https://cloud.githubusercontent.com/assets/872945/20936331/a6d8183c-bbfb-11e6-88b8-0d6b14b2c712.png)

while it should look like this:
![screenshot_20161206_203318](https://cloud.githubusercontent.com/assets/872945/20936334/a9f007f0-bbfb-11e6-9306-f7e3e23d770c.png)

So I looked into `zuluCrypt-gui-pkexec` file and used ``-K `id --user` `` part with `kdesudo`, like this: ``kdesudo "zuluCrypt-gui -K `id --user`"``

Now it uses my interface theme and is working fine (haven't checked everything, but basic stuff works, normal user owns created file containers, etc), except some minor glitches (like "The process for the file protocol died unexpectedly" error in file select windows).

So I wonder if this is ok to run zulucrypt like this or not (some security implications, maybe). If not, is there some way to make pkexec use my interface theme?

My system is Kubuntu 16.10 64-bit with zulucrypt 4.9.0-2, KDE Plasma 5.7.5, KDE Frameworks 5.26.0, Qt 5.6.1, kernel 4.8.0-30-generic if that matters.

**Comment by shvchk** [comment]
Forwarding `KDE_FULL_SESSION`, `XDG_RUNTIME_DIR`, `DISPLAY` and `XAUTHORITY` environment variables to `pkexec` seems to have the same effect, i.e. now it uses my interface theme, but also has "The process for the file protocol died unexpectedly" error (at the same time this error message is shown in terminal: `QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0`).

Command with forwarded env vars: ``pkexec env KDE_FULL_SESSION=$KDE_FULL_SESSION XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY "/usr/bin/zuluCrypt-gui" -K `id --user` "$@"``

**Comment by mhogomchungu** [comment]
Current maintainer of zuluCrypt here,
these work arounds are no longer necessary with properly packaged version 5.2.0 since GUI components run from a normal user account and the code that needs to be elevated runs in a separate CLI component called "zulupolkit".

**Comment by marciosouza20** [comment]
I will enable zulpolkit in the next Debian revision, I should do still in
September.

Em 5 de set de 2017 12:14 PM, "mhogomchungu" <notifications@github.com>
escreveu:

**Comment by marciosouza20** [comment]
Hi,

I believe that the issue you reported is fixed in the latest version of zulucrypt, the debian revision 5.2.0-2.  Thank you for reporting.

Changes:
 zulucrypt (5.2.0-2) unstable; urgency=medium
   * Created the files zulupolkit.install and zuluPolkit.1.
   * debian/control:
       - Bumped Standards-Version to 4.1.0.
       - Created the package zulupolkit to acomodated the new tool
         zuluPolkit.
       - Removed qtkeychain-dev from Build-Depends.
         Thanks Mhogo Mchungu (Closes: #875291).
   * debian/rules:
       - Enabled the polkit support at build time.
       - Updated file.
   * Removed the files because are unnecessary with zulupolkit:
       - The files zulu*-gui-pkexec and zulu*-gui-pkexec.1.
       - The files org.debian.pkexec.zulu*-gui.policy.
       - The files zulu*-gui.links.
   * Removed the files zulu*-gui.menu.
   * Updated the files zulu*-gui.desktop.
   * Updated the files zulu*-gui.install.
